-- 코드를 입력하세요
SELECT USER_ID, PRODUCT_ID
FROM (
    SELECT USER_ID, PRODUCT_ID, COUNT(*) AS purchase_count
    FROM ONLINE_SALE
    GROUP BY USER_ID, PRODUCT_ID
    HAVING purchase_count > 1
) AS repeated_purchases
ORDER BY USER_ID ASC, PRODUCT_ID DESC;